In [1]:
import numpy as np

# Input
k = int(input("Enter number of message bits (k): "))
r = int(input("Enter number of parity bits (r): "))

print("\nEnter Parity Matrix P (k x r):")
P = []
for i in range(k):
    row = list(map(int, input(f"Row {i+1}: ").split()))
    P.append(row)

P = np.array(P)

# Generator Matrix G = [P | I_k]
Ik = np.eye(k, dtype=int)
G = np.hstack((P, Ik))

n = k + r

# Parity Check Matrix H = [I_r | P^T]
Ir = np.eye(r, dtype=int)
H = np.hstack((Ir, P.T))

print("\nGenerator Matrix (G):")
print(G)

print("\nParity Check Matrix (H):")
print(H)

# Generate all possible message vectors
messages = np.array([[int(x) for x in format(i, f'0{k}b')] for i in range(2**k)])

# Generate Codewords
codewords = np.mod(messages @ G, 2)

print("\nMessage   Codeword   Hamming Weight")
weights = []
for m, c in zip(messages, codewords):
    w = np.sum(c)
    weights.append(w)
    print(m, "   ", c, "   ", w)

# Minimum Hamming distance
d_min = min(weights[1:])
print("\nMinimum Hamming Distance:", d_min)

# Receive codeword
rc = np.array(list(map(int, input("\nEnter received codeword: ").split())))

# Syndrome Calculation
syndrome = np.mod(rc @ H.T, 2)
print("\nSyndrome:", syndrome)

# Error detection
error_vector = np.zeros(n, dtype=int)

for i in range(n):
    if np.array_equal(H.T[i], syndrome):
        error_vector[i] = 1
        break

print("Error Vector:", error_vector)

# Error Correction (mod 2 addition)
corrected = np.mod(rc + error_vector, 2)
print("Corrected Codeword:", corrected)


Enter number of message bits (k): 3
Enter number of parity bits (r): 3

Enter Parity Matrix P (k x r):
Row 1: 1 0 0
Row 2: 1 0 1
Row 3: 1 1 0

Generator Matrix (G):
[[1 0 0 1 0 0]
 [1 0 1 0 1 0]
 [1 1 0 0 0 1]]

Parity Check Matrix (H):
[[1 0 0 1 1 1]
 [0 1 0 0 0 1]
 [0 0 1 0 1 0]]

Message   Codeword   Hamming Weight
[0 0 0]     [0 0 0 0 0 0]     0
[0 0 1]     [1 1 0 0 0 1]     3
[0 1 0]     [1 0 1 0 1 0]     3
[0 1 1]     [0 1 1 0 1 1]     4
[1 0 0]     [1 0 0 1 0 0]     2
[1 0 1]     [0 1 0 1 0 1]     3
[1 1 0]     [0 0 1 1 1 0]     3
[1 1 1]     [1 1 1 1 1 1]     6

Minimum Hamming Distance: 2

Enter received codeword: 0 3 3 4 2 3 3 6


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 8)